
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sterling_health?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    hibernate:
      ddl-auto: update


  resources:
    chain:
      cache: false

    cache:
      cachecontrol:
        max-age: 0



app:
  config:
    name: DEV



